version: "3"

services:
  node-app:
    container_name: express_node_app_container
    image: mohamedmagdy203/tresmerge-docker
    ports:
      - "5000:4000"
    env_file:
      - ./.env
    depends_on:
      - postgres-db
      - redis

  # mongo:
  #   image: mongo
  #   restart: always
  #   volumes:
  #     - mongo-db:/data/db
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  #     ME_CONFIG_BASICAUTH_ENABLED: true
  #     ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
  #     ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass
  #   depends_on:
  #     - mongo

  redis:
    image: redis
    ports:
      - "6379:6379"

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    depends_on:
      - node-app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydatabase
    volumes:
      - postgres-db:/var/lib/postgresql

volumes:
  mongo-db:
  postgres-db:
